inherit_from: ~/.rubocop.yml

AllCops:
  Exclude:
    - 'rubocop_pre_commit_hook.rb'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90

Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Max: 20